/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.forzaatleti.ejercicio0009.view;

import es.forzaatleti.ejercicio0009.model.Gestor;

/**
 *
 * @author cice
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfEdad = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSalida = new javax.swing.JTextArea();
        jbFor = new javax.swing.JButton();
        jbWhile = new javax.swing.JButton();
        jbDoWhile = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbMayorEdad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estructuras de Control y Repetición");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 51));

        jtfEdad.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jtfEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfEdad.setName("jtfEdad"); // NOI18N

        jbCalcular.setBackground(new java.awt.Color(255, 153, 0));
        jbCalcular.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCalcular.setText("Calcular");
        jbCalcular.setName("jbCalcular"); // NOI18N
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jtaSalida.setBackground(new java.awt.Color(0, 255, 255));
        jtaSalida.setColumns(20);
        jtaSalida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jtaSalida.setRows(5);
        jtaSalida.setAlignmentX(10.0F);
        jtaSalida.setName("jtaSalida"); // NOI18N
        jScrollPane1.setViewportView(jtaSalida);

        jbFor.setBackground(new java.awt.Color(255, 0, 51));
        jbFor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbFor.setText("Ejemplo for");
        jbFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbForActionPerformed(evt);
            }
        });

        jbWhile.setBackground(new java.awt.Color(51, 51, 255));
        jbWhile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbWhile.setForeground(new java.awt.Color(255, 255, 51));
        jbWhile.setText("Ejemplo While");
        jbWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbWhileActionPerformed(evt);
            }
        });

        jbDoWhile.setBackground(new java.awt.Color(0, 153, 255));
        jbDoWhile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDoWhile.setForeground(new java.awt.Color(255, 255, 255));
        jbDoWhile.setText("Ejemplo Do While");
        jbDoWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDoWhileActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(0, 0, 0));
        jbSalir.setForeground(new java.awt.Color(255, 255, 51));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbMayorEdad.setBackground(new java.awt.Color(255, 153, 0));
        jbMayorEdad.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jbMayorEdad.setText("¿Es mayor de Edad?");
        jbMayorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMayorEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbMayorEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbFor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbWhile, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbDoWhile)
                        .addContainerGap(322, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbWhile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbFor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMayorEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jbDoWhile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addComponent(jbSalir))
                    .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
           // TODO add your handling code here:
           System.out.println("Botón pulsado");
           int edad = Integer.parseInt(jtfEdad.getText());
           String mensaje = Gestor.calcularSegmento(edad);
           jtaSalida.setText(mensaje);
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbForActionPerformed
        // TODO add your handling code here:
        jtaSalida.setText("Ejemplo FOR: \n\n");
        for (int i = 0; i < 10; i++) {
            jtaSalida.append("FOR: " + i + "\n");
        }
    }//GEN-LAST:event_jbForActionPerformed

    private void jbWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbWhileActionPerformed
        // TODO add your handling code here:
        int i = 0;

        jtaSalida.setText("Ejemplo WHILE: \n\n");

        while (i < 10) {
            jtaSalida.append("WHILE: " + i + "\n");
            i++;
        }
    }//GEN-LAST:event_jbWhileActionPerformed

    private void jbDoWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDoWhileActionPerformed
        // TODO add your handling code here:
        int i = 0;

        jtaSalida.setText("Ejemplo DO WHILE: \n\n");

        do {
            jtaSalida.append("DO WHILE: " + i + "\n");
            i++;
        } while (i < 10);
    }//GEN-LAST:event_jbDoWhileActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbMayorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMayorEdadActionPerformed
        // TODO add your handling code here:
        jtaSalida.setText("Es mayor de Edad?: \n\n");
           int edad = Integer.parseInt(jtfEdad.getText());
           boolean mensaje = Gestor.esMayorEdad(edad);
           
           jtaSalida.setText(mensaje);
    }//GEN-LAST:event_jbMayorEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbDoWhile;
    private javax.swing.JButton jbFor;
    private javax.swing.JButton jbMayorEdad;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbWhile;
    private javax.swing.JTextArea jtaSalida;
    private javax.swing.JTextField jtfEdad;
    // End of variables declaration//GEN-END:variables
}
